TOMTOM_API_KEY = "zJT5UBCDtRKSWwsbGp6LWjcQcIi0IcdV"
TOMTOM_API_KEY2 = "mZDEYNoQdyiV6OLAndYGHN4n3dkv7TVc"
TOMTOM_API_KEY3 = "NrTBKSNwf4EsJ8FdbAhYApV6LEMcwhWG"

CALENDAR_API_KEY = "I1Htwnn7JBKzCjogaMxoW2T1WW8ew47R"

HOPSWORKS_API_KEY = ''