# Workflow 1: Update Traffic Information
name: Update Model
on:
  schedule:
    - cron: '0 6 * * *'  # Run every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_traffic:
    name: Update Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter

      - name: Set Python Path
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Set environment variables for API Keys
        run: |
          echo "HOPSWORKS_API_KEY=${{ secrets.HOPSWORKS_API_KEY }}" >> $GITHUB_ENV

      - name: Run update traffic notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace notebooks/Training.ipynb

